
package com.webservice.consumer.business;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BusinessCenterServiceInterface", targetNamespace = "http://export.service.joyoung.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BusinessCenterServiceInterface {


    /**
     * 
     * @param serviceVersion
     * @param serviceCode
     * @param userPwd
     * @param sign
     * @param parm
     * @param page
     * @param userName
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(action = "http://export.service.joyoung.com/callService")
    @WebResult(targetNamespace = "http://export.service.joyoung.com/")
    @RequestWrapper(localName = "callService", targetNamespace = "http://export.service.joyoung.com/", className = "com.webservice.consumer.business.CallService")
    @ResponseWrapper(localName = "callServiceResponse", targetNamespace = "http://export.service.joyoung.com/", className = "com.webservice.consumer.business.CallServiceResponse")
    public List<String> callService(
        @WebParam(name = "serviceCode", targetNamespace = "http://export.service.joyoung.com/")
        String serviceCode,
        @WebParam(name = "serviceVersion", targetNamespace = "http://export.service.joyoung.com/")
        String serviceVersion,
        @WebParam(name = "userName", targetNamespace = "http://export.service.joyoung.com/")
        String userName,
        @WebParam(name = "userPwd", targetNamespace = "http://export.service.joyoung.com/")
        String userPwd,
        @WebParam(name = "sign", targetNamespace = "http://export.service.joyoung.com/")
        String sign,
        @WebParam(name = "parm", targetNamespace = "http://export.service.joyoung.com/")
        String parm,
        @WebParam(name = "page", targetNamespace = "http://export.service.joyoung.com/")
        String page);

}
